# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.0-browsers
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
